name: Java Web Server CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          java-package: jdk
          architecture: x64
          distribution: temurin


      - name: Build and test
        run: |
          mvn clean install -f ./my-project

      - name: Deploy to EC2 using Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
          cli_config_credentials_token: ${{ secrets.AWS_ACCESS_TOKEN }}
          aws_region: us-east-1

      - name: Configure AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: |
          terraform init
          terraform apply -auto-approve -var "private_key_path=${{ secrets.PRIVATE_KEY_PATH }}"

      - name: Deploy using Terraform
        run: |
          terraform apply -auto-approve
