name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust the Java version as needed
          distribution: 'adopt'  # Use 'adopt' or 'temurin' as the distribution provider

      - name: Build with Maven
        run: mvn -f java/pom.xml clean package  # Replace 'path/to/project' with the actual path to your project

      - name: Run unit tests
        run: mvn -f java/pom.xml test  # Replace 'path/to/project' with the actual path to project

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
          audience: sts.amazonaws.com


      - name: Deploy with Terraform
        run: |
          cd terraform
          terraform init
          terraform plan
          terraform apply --auto-approve
